### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by colewebb** [colewebb/group-8#1]
[Security issues found by GitHub's automated services](https://github.com/colewebb/usu-cs3450-group/security/dependabot)

I'm not sufficiently familiar with React to know what exactly is going on here.

@austinGENEreeve Thoughts?

**Comment by austinGENEreeve** [comment]
The link is giving me a 404.. I'm logged in so I'm not sure why I can't see it

**Comment by colewebb** [comment]
Me too. I'll look into it in the morning

**Comment by colewebb** [comment]
This won't be fixed in the development version.
