### ISSUE TITLE
Customer access features part 1

### ISSUE THREAD

**Issue by logansmith283** [colewebb/group-8#11]
Customers will have access to the following features:
- access to their profile page.
- list of dates and events coming up.
- after selecting a date and event, available lots will be shown with their relative location to the event and the price and number of available spots.

**Comment by austinGENEreeve** [comment]
I've added navigation to the app. We need to connect this weekend to merge our code as we have things that will over lap. It should be a quick merge but we will need to work together on it. :)

**Comment by colewebb** [comment]
Size: L
