### ISSUE TITLE
sign up/register api

### ISSUE THREAD

**Issue by austinGENEreeve** [colewebb/group-8#24]

**Comment by austinGENEreeve** [comment]
I need to connect with @logansmith283 and @JeremyCodes20 to make sure the authentication works with our schema and API's. We plan on working together Sunday

**Comment by JeremyCodes20** [comment]
3/22: Authentication is working, need to write a view for login and signup

**Comment by JeremyCodes20** [comment]
3/24: Tentative api calls made for login and register. Need to be tested by front-end

**Comment by colewebb** [comment]
Size: L

**Comment by colewebb** [comment]
Size: L
