### ISSUE TITLE
Customer access features part 2 (Checkout process)

### ISSUE THREAD

**Issue by logansmith283** [colewebb/group-8#28]
- Customers will have access to a page with their current reservations listed. These reservations may be updated (change the car details if they plan on taking a different vehicle).
- a checkout page where total price is displayed, and customer is required to add information such as make, model, color and license plate of the vehicle they plan on parking.
- after continuing, payment amount will be subtracted from the customers balance.
- Customers will be given a QR code after checkout, this may also be emailed to them. This will be used for checking in at the parking lot on the date of the event.

**Comment by colewebb** [comment]
Size: L

**Comment by colewebb** [comment]
Size: L
