### ISSUE TITLE
Run Django and React

### ISSUE THREAD

**Issue by colewebb** [colewebb/group-8#29]
Everyone needs to be able to run Django and React. Please comment when you accomplish this

**Comment by colewebb** [comment]
I have completed this

**Comment by austinGENEreeve** [comment]
I have completed this. Running both! :)

**Comment by austinGENEreeve** [comment]
@JeremyCodes20 @logansmith283 Don't forget to comment on this so we can close it for sprint 1

**Comment by colewebb** [comment]
Closed; everyone has the software they need, and help is available in case that changes.
