### ISSUE TITLE
Conceptual Model

### ISSUE THREAD

**Issue by colewebb** [colewebb/group-8#6]
- Use case diagrams that document the actors and their goals
- Class diagrams that document the classes of objects in the system and their relationships
- Activity diagrams that document key execution flows

**Comment by JeremyCodes20** [comment]
Activity Diagrams draw.io added to Google Drive. 1 diagram completed detailing the process for purchasing a ticket.

**Comment by JeremyCodes20** [comment]
Two more activity diagrams added.

**Comment by JeremyCodes20** [comment]
Two more activity diagrams added.

**Comment by JeremyCodes20** [comment]
Activity diagrams finished. Commit 81a28dc4fc324c5ed4a6623bb9f50c9a986303d0

**Comment by JeremyCodes20** [comment]
Class diagrams finished as a group. Commit e617758ef9a2c6482d0dbe549f84403c1d0fe21d
This resolves this issue.
